name: GitHub Pages'a Yayinla

on:
  push:
    branches:
      - main
      - master
      - playtvapp41.github.io

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Node.js Kurulumu ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Bagimliliklari Yukle 📦
        run: |
          rm -f package-lock.json
          npm install
          npm install --save-dev @tailwindcss/oxide-linux-x64

      - name: Projeyi Derle (Build) 🏗️
        run: npm run build

      - name: GitHub Pages'a Yukle (Deploy) 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
